// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator, DO NOT EDIT.

package orgthehostergitlabtrackrd

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/varlink/go/varlink"
)

// Generated type declarations

type Issue struct {
	Id           int64  `json:"id"`
	Iid          int64  `json:"iid"`
	Project_id   int64  `json:"project_id"`
	Title        string `json:"title"`
	Web_url      string `json:"web_url"`
	State        string `json:"state"`
	Parent       string `json:"parent"`
	Total_time   string `json:"total_time"`
	Graph_status string `json:"graph_status"`
}

type HistoryEvent struct {
	Timestamp   int64  `json:"timestamp"`
	Source      string `json:"source"`
	Project_id  int64  `json:"project_id"`
	Issue_iid   int64  `json:"issue_iid"`
	Issue_title string `json:"issue_title"`
	Web_url     string `json:"web_url"`
	Duration    string `json:"duration"`
	Summary     string `json:"summary"`
}

type FailedTask struct {
	Id         int64  `json:"id"`
	Op         string `json:"op"`
	Project_id int64  `json:"project_id"`
	Issue_iid  int64  `json:"issue_iid"`
	Detail     string `json:"detail"`
	Error      string `json:"error"`
	Queued_at  int64  `json:"queued_at"`
	Failed_at  int64  `json:"failed_at"`
}

type NotAuthReason string

type GitlabError struct {
	Message string `json:"message"`
}

func (e GitlabError) Error() string {
	s := "org.thehoster.gitlab.trackrd.GitlabError"
	s += fmt.Sprintf("(Message: %v)", e.Message)
	return s
}

type NotAuthenticated struct {
	Reason *NotAuthReason `json:"reason,omitempty"`
	Detail *string        `json:"detail,omitempty"`
}

func (e NotAuthenticated) Error() string {
	s := "org.thehoster.gitlab.trackrd.NotAuthenticated"
	s += fmt.Sprintf("(Reason: %v, Detail: %v)", e.Reason, e.Detail)
	return s
}

func Dispatch_Error(err error) error {
	if e, ok := err.(*varlink.Error); ok {
		switch e.Name {
		case "org.thehoster.gitlab.trackrd.GitlabError":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param GitlabError
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		case "org.thehoster.gitlab.trackrd.NotAuthenticated":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param NotAuthenticated
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		}
	}
	return err
}

// Generated client method calls

type GetAssignedIssues_methods struct{}

func GetAssignedIssues() GetAssignedIssues_methods { return GetAssignedIssues_methods{} }

func (m GetAssignedIssues_methods) Call(ctx context.Context, c *varlink.Connection, groups_in_ *[]string) (issues_out_ []Issue, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, groups_in_)
	if err_ != nil {
		return
	}
	issues_out_, _, err_ = receive(ctx)
	return
}

func (m GetAssignedIssues_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, groups_in_ *[]string) (func(ctx context.Context) ([]Issue, uint64, error), error) {
	var in struct {
		Groups *[]string `json:"groups,omitempty"`
	}
	in.Groups = groups_in_
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.GetAssignedIssues", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (issues_out_ []Issue, flags uint64, err error) {
		var out struct {
			Issues []Issue `json:"issues"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		issues_out_ = []Issue(out.Issues)
		return
	}, nil
}

func (m GetAssignedIssues_methods) Upgrade(ctx context.Context, c *varlink.Connection, groups_in_ *[]string) (func(ctx context.Context) (issues_out_ []Issue, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Groups *[]string `json:"groups,omitempty"`
	}
	in.Groups = groups_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.GetAssignedIssues", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (issues_out_ []Issue, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Issues []Issue `json:"issues"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		issues_out_ = []Issue(out.Issues)
		return
	}, nil
}

type PostTime_methods struct{}

func PostTime() PostTime_methods { return PostTime_methods{} }

func (m PostTime_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, issue_iid_in_ int64, duration_in_ string, summary_in_ *string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, issue_iid_in_, duration_in_, summary_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m PostTime_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, issue_iid_in_ int64, duration_in_ string, summary_in_ *string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64   `json:"project_id"`
		Issue_iid  int64   `json:"issue_iid"`
		Duration   string  `json:"duration"`
		Summary    *string `json:"summary,omitempty"`
	}
	in.Project_id = project_id_in_
	in.Issue_iid = issue_iid_in_
	in.Duration = duration_in_
	in.Summary = summary_in_
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.PostTime", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m PostTime_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, issue_iid_in_ int64, duration_in_ string, summary_in_ *string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64   `json:"project_id"`
		Issue_iid  int64   `json:"issue_iid"`
		Duration   string  `json:"duration"`
		Summary    *string `json:"summary,omitempty"`
	}
	in.Project_id = project_id_in_
	in.Issue_iid = issue_iid_in_
	in.Duration = duration_in_
	in.Summary = summary_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.PostTime", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type CloseIssue_methods struct{}

func CloseIssue() CloseIssue_methods { return CloseIssue_methods{} }

func (m CloseIssue_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, issue_iid_in_ int64) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, issue_iid_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m CloseIssue_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, issue_iid_in_ int64) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64 `json:"project_id"`
		Issue_iid  int64 `json:"issue_iid"`
	}
	in.Project_id = project_id_in_
	in.Issue_iid = issue_iid_in_
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.CloseIssue", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m CloseIssue_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, issue_iid_in_ int64) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64 `json:"project_id"`
		Issue_iid  int64 `json:"issue_iid"`
	}
	in.Project_id = project_id_in_
	in.Issue_iid = issue_iid_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.CloseIssue", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type AssignSelf_methods struct{}

func AssignSelf() AssignSelf_methods { return AssignSelf_methods{} }

func (m AssignSelf_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, issue_iid_in_ int64) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, issue_iid_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m AssignSelf_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, issue_iid_in_ int64) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64 `json:"project_id"`
		Issue_iid  int64 `json:"issue_iid"`
	}
	in.Project_id = project_id_in_
	in.Issue_iid = issue_iid_in_
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.AssignSelf", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m AssignSelf_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, issue_iid_in_ int64) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64 `json:"project_id"`
		Issue_iid  int64 `json:"issue_iid"`
	}
	in.Project_id = project_id_in_
	in.Issue_iid = issue_iid_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.AssignSelf", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type UnassignSelf_methods struct{}

func UnassignSelf() UnassignSelf_methods { return UnassignSelf_methods{} }

func (m UnassignSelf_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, issue_iid_in_ int64) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, issue_iid_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m UnassignSelf_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, issue_iid_in_ int64) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64 `json:"project_id"`
		Issue_iid  int64 `json:"issue_iid"`
	}
	in.Project_id = project_id_in_
	in.Issue_iid = issue_iid_in_
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.UnassignSelf", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m UnassignSelf_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, issue_iid_in_ int64) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64 `json:"project_id"`
		Issue_iid  int64 `json:"issue_iid"`
	}
	in.Project_id = project_id_in_
	in.Issue_iid = issue_iid_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.UnassignSelf", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type ClearCache_methods struct{}

func ClearCache() ClearCache_methods { return ClearCache_methods{} }

func (m ClearCache_methods) Call(ctx context.Context, c *varlink.Connection, scope_in_ *[]string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, scope_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m ClearCache_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, scope_in_ *[]string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Scope *[]string `json:"scope,omitempty"`
	}
	in.Scope = scope_in_
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.ClearCache", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m ClearCache_methods) Upgrade(ctx context.Context, c *varlink.Connection, scope_in_ *[]string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Scope *[]string `json:"scope,omitempty"`
	}
	in.Scope = scope_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.ClearCache", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type GetHistory_methods struct{}

func GetHistory() GetHistory_methods { return GetHistory_methods{} }

func (m GetHistory_methods) Call(ctx context.Context, c *varlink.Connection, days_in_ *int64) (events_out_ []HistoryEvent, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, days_in_)
	if err_ != nil {
		return
	}
	events_out_, _, err_ = receive(ctx)
	return
}

func (m GetHistory_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, days_in_ *int64) (func(ctx context.Context) ([]HistoryEvent, uint64, error), error) {
	var in struct {
		Days *int64 `json:"days,omitempty"`
	}
	in.Days = days_in_
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.GetHistory", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (events_out_ []HistoryEvent, flags uint64, err error) {
		var out struct {
			Events []HistoryEvent `json:"events"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		events_out_ = []HistoryEvent(out.Events)
		return
	}, nil
}

func (m GetHistory_methods) Upgrade(ctx context.Context, c *varlink.Connection, days_in_ *int64) (func(ctx context.Context) (events_out_ []HistoryEvent, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Days *int64 `json:"days,omitempty"`
	}
	in.Days = days_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.GetHistory", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (events_out_ []HistoryEvent, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Events []HistoryEvent `json:"events"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		events_out_ = []HistoryEvent(out.Events)
		return
	}, nil
}

type GetFailures_methods struct{}

func GetFailures() GetFailures_methods { return GetFailures_methods{} }

func (m GetFailures_methods) Call(ctx context.Context, c *varlink.Connection) (failures_out_ []FailedTask, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	failures_out_, _, err_ = receive(ctx)
	return
}

func (m GetFailures_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) ([]FailedTask, uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.GetFailures", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (failures_out_ []FailedTask, flags uint64, err error) {
		var out struct {
			Failures []FailedTask `json:"failures"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		failures_out_ = []FailedTask(out.Failures)
		return
	}, nil
}

func (m GetFailures_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (failures_out_ []FailedTask, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.GetFailures", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (failures_out_ []FailedTask, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Failures []FailedTask `json:"failures"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		failures_out_ = []FailedTask(out.Failures)
		return
	}, nil
}

type RetryFailure_methods struct{}

func RetryFailure() RetryFailure_methods { return RetryFailure_methods{} }

func (m RetryFailure_methods) Call(ctx context.Context, c *varlink.Connection, id_in_ int64) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, id_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m RetryFailure_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, id_in_ int64) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Id int64 `json:"id"`
	}
	in.Id = id_in_
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.RetryFailure", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m RetryFailure_methods) Upgrade(ctx context.Context, c *varlink.Connection, id_in_ int64) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Id int64 `json:"id"`
	}
	in.Id = id_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.RetryFailure", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type DismissFailure_methods struct{}

func DismissFailure() DismissFailure_methods { return DismissFailure_methods{} }

func (m DismissFailure_methods) Call(ctx context.Context, c *varlink.Connection, id_in_ int64) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, id_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m DismissFailure_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, id_in_ int64) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Id int64 `json:"id"`
	}
	in.Id = id_in_
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.DismissFailure", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m DismissFailure_methods) Upgrade(ctx context.Context, c *varlink.Connection, id_in_ int64) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Id int64 `json:"id"`
	}
	in.Id = id_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.DismissFailure", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type ClearFailures_methods struct{}

func ClearFailures() ClearFailures_methods { return ClearFailures_methods{} }

func (m ClearFailures_methods) Call(ctx context.Context, c *varlink.Connection) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m ClearFailures_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.ClearFailures", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m ClearFailures_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.ClearFailures", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type Login_methods struct{}

func Login() Login_methods { return Login_methods{} }

func (m Login_methods) Call(ctx context.Context, c *varlink.Connection, host_in_ string, token_in_ string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, host_in_, token_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m Login_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, host_in_ string, token_in_ string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Host  string `json:"host"`
		Token string `json:"token"`
	}
	in.Host = host_in_
	in.Token = token_in_
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.Login", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m Login_methods) Upgrade(ctx context.Context, c *varlink.Connection, host_in_ string, token_in_ string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Host  string `json:"host"`
		Token string `json:"token"`
	}
	in.Host = host_in_
	in.Token = token_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.Login", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type Logout_methods struct{}

func Logout() Logout_methods { return Logout_methods{} }

func (m Logout_methods) Call(ctx context.Context, c *varlink.Connection) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m Logout_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.Logout", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m Logout_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.Logout", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type WhoAmI_methods struct{}

func WhoAmI() WhoAmI_methods { return WhoAmI_methods{} }

func (m WhoAmI_methods) Call(ctx context.Context, c *varlink.Connection) (host_out_ string, user_id_out_ int64, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	host_out_, user_id_out_, _, err_ = receive(ctx)
	return
}

func (m WhoAmI_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (string, int64, uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.gitlab.trackrd.WhoAmI", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (host_out_ string, user_id_out_ int64, flags uint64, err error) {
		var out struct {
			Host    string `json:"host"`
			User_id int64  `json:"user_id"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		host_out_ = out.Host
		user_id_out_ = out.User_id
		return
	}, nil
}

func (m WhoAmI_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (host_out_ string, user_id_out_ int64, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.gitlab.trackrd.WhoAmI", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (host_out_ string, user_id_out_ int64, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Host    string `json:"host"`
			User_id int64  `json:"user_id"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		host_out_ = out.Host
		user_id_out_ = out.User_id
		return
	}, nil
}

// Generated service interface with all methods

type orgthehostergitlabtrackrdInterface interface {
	GetAssignedIssues(ctx context.Context, c VarlinkCall, groups_ *[]string) error
	PostTime(ctx context.Context, c VarlinkCall, project_id_ int64, issue_iid_ int64, duration_ string, summary_ *string) error
	CloseIssue(ctx context.Context, c VarlinkCall, project_id_ int64, issue_iid_ int64) error
	AssignSelf(ctx context.Context, c VarlinkCall, project_id_ int64, issue_iid_ int64) error
	UnassignSelf(ctx context.Context, c VarlinkCall, project_id_ int64, issue_iid_ int64) error
	ClearCache(ctx context.Context, c VarlinkCall, scope_ *[]string) error
	GetHistory(ctx context.Context, c VarlinkCall, days_ *int64) error
	GetFailures(ctx context.Context, c VarlinkCall) error
	RetryFailure(ctx context.Context, c VarlinkCall, id_ int64) error
	DismissFailure(ctx context.Context, c VarlinkCall, id_ int64) error
	ClearFailures(ctx context.Context, c VarlinkCall) error
	Login(ctx context.Context, c VarlinkCall, host_ string, token_ string) error
	Logout(ctx context.Context, c VarlinkCall) error
	WhoAmI(ctx context.Context, c VarlinkCall) error
}

// Generated service object with all methods

type VarlinkCall struct{ varlink.Call }

// Generated reply methods for all varlink errors

func (c *VarlinkCall) ReplyGitlabError(ctx context.Context, message_ string) error {
	var out GitlabError
	out.Message = message_
	return c.ReplyError(ctx, "org.thehoster.gitlab.trackrd.GitlabError", &out)
}

func (c *VarlinkCall) ReplyNotAuthenticated(ctx context.Context, reason_ *NotAuthReason, detail_ *string) error {
	var out NotAuthenticated
	out.Reason = reason_
	out.Detail = detail_
	return c.ReplyError(ctx, "org.thehoster.gitlab.trackrd.NotAuthenticated", &out)
}

// Generated reply methods for all varlink methods

func (c *VarlinkCall) ReplyGetAssignedIssues(ctx context.Context, issues_ []Issue) error {
	var out struct {
		Issues []Issue `json:"issues"`
	}
	out.Issues = []Issue(issues_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyPostTime(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyCloseIssue(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyAssignSelf(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyUnassignSelf(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyClearCache(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyGetHistory(ctx context.Context, events_ []HistoryEvent) error {
	var out struct {
		Events []HistoryEvent `json:"events"`
	}
	out.Events = []HistoryEvent(events_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyGetFailures(ctx context.Context, failures_ []FailedTask) error {
	var out struct {
		Failures []FailedTask `json:"failures"`
	}
	out.Failures = []FailedTask(failures_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyRetryFailure(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyDismissFailure(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyClearFailures(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyLogin(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyLogout(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyWhoAmI(ctx context.Context, host_ string, user_id_ int64) error {
	var out struct {
		Host    string `json:"host"`
		User_id int64  `json:"user_id"`
	}
	out.Host = host_
	out.User_id = user_id_
	return c.Reply(ctx, &out)
}

// Generated dummy implementations for all varlink methods

func (s *VarlinkInterface) GetAssignedIssues(ctx context.Context, c VarlinkCall, groups_ *[]string) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.GetAssignedIssues")
}

func (s *VarlinkInterface) PostTime(ctx context.Context, c VarlinkCall, project_id_ int64, issue_iid_ int64, duration_ string, summary_ *string) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.PostTime")
}

func (s *VarlinkInterface) CloseIssue(ctx context.Context, c VarlinkCall, project_id_ int64, issue_iid_ int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.CloseIssue")
}

func (s *VarlinkInterface) AssignSelf(ctx context.Context, c VarlinkCall, project_id_ int64, issue_iid_ int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.AssignSelf")
}

func (s *VarlinkInterface) UnassignSelf(ctx context.Context, c VarlinkCall, project_id_ int64, issue_iid_ int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.UnassignSelf")
}

func (s *VarlinkInterface) ClearCache(ctx context.Context, c VarlinkCall, scope_ *[]string) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.ClearCache")
}

func (s *VarlinkInterface) GetHistory(ctx context.Context, c VarlinkCall, days_ *int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.GetHistory")
}

func (s *VarlinkInterface) GetFailures(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.GetFailures")
}

func (s *VarlinkInterface) RetryFailure(ctx context.Context, c VarlinkCall, id_ int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.RetryFailure")
}

func (s *VarlinkInterface) DismissFailure(ctx context.Context, c VarlinkCall, id_ int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.DismissFailure")
}

func (s *VarlinkInterface) ClearFailures(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.ClearFailures")
}

func (s *VarlinkInterface) Login(ctx context.Context, c VarlinkCall, host_ string, token_ string) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.Login")
}

func (s *VarlinkInterface) Logout(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.Logout")
}

func (s *VarlinkInterface) WhoAmI(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.gitlab.trackrd.WhoAmI")
}

// Generated method call dispatcher

func (s *VarlinkInterface) VarlinkDispatch(ctx context.Context, call varlink.Call, methodname string) error {
	switch methodname {
	case "GetAssignedIssues":
		var in struct {
			Groups *[]string `json:"groups,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehostergitlabtrackrdInterface.GetAssignedIssues(ctx, VarlinkCall{call}, in.Groups)

	case "PostTime":
		var in struct {
			Project_id int64   `json:"project_id"`
			Issue_iid  int64   `json:"issue_iid"`
			Duration   string  `json:"duration"`
			Summary    *string `json:"summary,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehostergitlabtrackrdInterface.PostTime(ctx, VarlinkCall{call}, in.Project_id, in.Issue_iid, in.Duration, in.Summary)

	case "CloseIssue":
		var in struct {
			Project_id int64 `json:"project_id"`
			Issue_iid  int64 `json:"issue_iid"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehostergitlabtrackrdInterface.CloseIssue(ctx, VarlinkCall{call}, in.Project_id, in.Issue_iid)

	case "AssignSelf":
		var in struct {
			Project_id int64 `json:"project_id"`
			Issue_iid  int64 `json:"issue_iid"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehostergitlabtrackrdInterface.AssignSelf(ctx, VarlinkCall{call}, in.Project_id, in.Issue_iid)

	case "UnassignSelf":
		var in struct {
			Project_id int64 `json:"project_id"`
			Issue_iid  int64 `json:"issue_iid"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehostergitlabtrackrdInterface.UnassignSelf(ctx, VarlinkCall{call}, in.Project_id, in.Issue_iid)

	case "ClearCache":
		var in struct {
			Scope *[]string `json:"scope,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehostergitlabtrackrdInterface.ClearCache(ctx, VarlinkCall{call}, in.Scope)

	case "GetHistory":
		var in struct {
			Days *int64 `json:"days,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehostergitlabtrackrdInterface.GetHistory(ctx, VarlinkCall{call}, in.Days)

	case "GetFailures":
		return s.orgthehostergitlabtrackrdInterface.GetFailures(ctx, VarlinkCall{call})

	case "RetryFailure":
		var in struct {
			Id int64 `json:"id"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehostergitlabtrackrdInterface.RetryFailure(ctx, VarlinkCall{call}, in.Id)

	case "DismissFailure":
		var in struct {
			Id int64 `json:"id"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehostergitlabtrackrdInterface.DismissFailure(ctx, VarlinkCall{call}, in.Id)

	case "ClearFailures":
		return s.orgthehostergitlabtrackrdInterface.ClearFailures(ctx, VarlinkCall{call})

	case "Login":
		var in struct {
			Host  string `json:"host"`
			Token string `json:"token"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehostergitlabtrackrdInterface.Login(ctx, VarlinkCall{call}, in.Host, in.Token)

	case "Logout":
		return s.orgthehostergitlabtrackrdInterface.Logout(ctx, VarlinkCall{call})

	case "WhoAmI":
		return s.orgthehostergitlabtrackrdInterface.WhoAmI(ctx, VarlinkCall{call})

	default:
		return call.ReplyMethodNotFound(ctx, methodname)
	}
}

// Generated varlink interface name

func (s *VarlinkInterface) VarlinkGetName() string {
	return `org.thehoster.gitlab.trackrd`
}

// Generated varlink interface description

func (s *VarlinkInterface) VarlinkGetDescription() string {
	return `interface org.thehoster.gitlab.trackrd

type Issue (
  id: int,
  iid: int,
  project_id: int,
  title: string,
  web_url: string,
  state: string,
  parent: string,
  total_time: string,
  graph_status: string
)

type HistoryEvent (
  timestamp: int,
  source: string,
  project_id: int,
  issue_iid: int,
  issue_title: string,
  web_url: string,
  duration: string,
  summary: string
)

type FailedTask (
  id: int,
  op: string,
  project_id: int,
  issue_iid: int,
  detail: string,
  error: string,
  queued_at: int,
  failed_at: int
)

error GitlabError (message: string)

type NotAuthReason (no_credentials, keychain_error, unreachable, token_rejected, logged_out)

error NotAuthenticated (reason: ?NotAuthReason, detail: ?string)

method GetAssignedIssues(groups: ?[]string) -> (issues: []Issue)

method PostTime(project_id: int, issue_iid: int, duration: string, summary: ?string) -> ()

method CloseIssue(project_id: int, issue_iid: int) -> ()

method AssignSelf(project_id: int, issue_iid: int) -> ()

method UnassignSelf(project_id: int, issue_iid: int) -> ()

method ClearCache(scope: ?[]string) -> ()

method GetHistory(days: ?int) -> (events: []HistoryEvent)

method GetFailures() -> (failures: []FailedTask)

method RetryFailure(id: int) -> ()

method DismissFailure(id: int) -> ()

method ClearFailures() -> ()

method Login(host: string, token: string) -> ()

method Logout() -> ()

method WhoAmI() -> (host: string, user_id: int)
`
}

// Generated service interface

type VarlinkInterface struct {
	orgthehostergitlabtrackrdInterface
}

func VarlinkNew(m orgthehostergitlabtrackrdInterface) *VarlinkInterface {
	return &VarlinkInterface{m}
}
